# Generate the files

## Requirements

[rustup](https://rustup.rs/)
[python3](https://www.python.org/downloads/)

Maybe virtual env?

## Step by Step
We need to locate the directory where the replays are, in my case I dual-boot and mount windows to `/mnt/windows`

The final step takes around 32 seconds to process 3600 Replay files. This means about 110 replays per-second on a 16 Core machine.
```bash
$ git clone https://github.com/sebosp/s2protocol-rs
$ cd s2protocol-rs
$ mkdir -p ipcs/
$ cargo run -r --no-default-features --features=dep_arrow,tracing_off -- -v error --timing --source $HOME/SCReplaysOnNVMe --json-balance-data-dir $PWD/assets/BalanceData/ --output $HOME/git/s2protocol-rs/ipcs/ write-arrow-ipc
36877 files have valid init data, processing...
Total time: 434.331297522s
seb in 🌐 corvid in s2protocol-rs on  main is 📦 v3.4.0 via 🦀 v1.89.0 took 7m16s
❯ du -sh ipcs/*
3.3G    ipcs/cmd_target_point.ipc
960M    ipcs/cmd_target_unit.ipc
9.7M    ipcs/details.ipc
113M    ipcs/lobby_init_data.ipc
2.1G    ipcs/stats.ipc
9.4G    ipcs/unit_born.ipc
5.6G    ipcs/unit_died.ipc
172M    ipcs/upgrades.ipc
$ cd ../s2-polars-data-analysis/
$ pip install -r requirements.txt
$ jupyter lab --notebook-dir=jupyter_notebooks/
# Open the URL explained in the terminal, this will open this notebook for interacting with the data.
```

In [1]:
# import datashader as ds
import plotly.express as px
import polars as pl

pl.Config.set_tbl_width_chars(256)
pl.Config.set_fmt_str_lengths(256)
pl.Config.set_tbl_rows(24)

# Location of the IPC generated files from above.
ipc_dir = "/home/seb/git/s2protocol-rs/ipcs"

unit_born_df = pl.scan_ipc(f"{ipc_dir}/unit_born.ipc")
unit_died_df = pl.scan_ipc(f"{ipc_dir}/unit_died.ipc")
stats_df = pl.scan_ipc(f"{ipc_dir}/stats.ipc")
upgrades_df = pl.scan_ipc(f"{ipc_dir}/upgrades.ipc")
lobby_slot_init_data_df = pl.scan_ipc(f"{ipc_dir}/lobby_init_data.ipc")
user_init_data_df = pl.scan_ipc(f"{ipc_dir}/user_init_data.ipc")
details_df = pl.scan_ipc(f"{ipc_dir}/details.ipc")
cmd_target_point_df = pl.scan_ipc(f"{ipc_dir}/cmd_target_point.ipc")
cmd_target_unit_df = pl.scan_ipc(f"{ipc_dir}/cmd_target_unit.ipc")

# Find a game:
lobby_slot_init_data_df.filter(
    [
        pl.col("ext_fs_file_name").str.contains("Grand Finals")
        & pl.col("ext_fs_file_name").str.contains("2025")
        & pl.col("observe").eq(0)
    ]
).collect()

shape: (14, 10)
┌───────────┬──────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────┬─────────┬───┬─────────┬─────────────────────┬────────────┬────────────┐
│ ext_fs_id ┆ ext_fs_sha256                                                    ┆ ext_fs_file_name                                                                      ┆ control ┆ … ┆ observe ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---       ┆ ---                                                              ┆ ---                                                                                   ┆ ---     ┆   ┆ ---     ┆ ---                 ┆ ---        ┆ ---        │
│ u64       ┆ str                                                              ┆ str                                                                                   ┆ i64     ┆   ┆ u8      ┆ u8                  ┆ u8         ┆ u8         │
╞═══════════╪══════════════════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════════════════════════════════════╪═════════╪═══╪═════════╪═════════════════════╪════════════╪════════════╡
│ 16715     ┆ 035622859a854c30852e566a11e0600aa1041fc7b327254146e04469362a4786 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 11                  ┆ 184        ┆ 184        │
│           ┆                                                                  ┆ Classic/20250725 - Game3 - Classic vs Serral - Ultralove.SC2Replay                    ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16715     ┆ 035622859a854c30852e566a11e0600aa1041fc7b327254146e04469362a4786 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 12                  ┆ 184        ┆ 184        │
│           ┆                                                                  ┆ Classic/20250725 - Game3 - Classic vs Serral - Ultralove.SC2Replay                    ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16716     ┆ e79a9db4ae3fea38c557cb798e8bd712220f4517b37b3cf51cc5f12e5114af64 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 11                  ┆ 248        ┆ 250        │
│           ┆                                                                  ┆ Classic/20250725 - Game4 - Classic vs Serral - Pylon.SC2Replay                        ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16716     ┆ e79a9db4ae3fea38c557cb798e8bd712220f4517b37b3cf51cc5f12e5114af64 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 14                  ┆ 248        ┆ 250        │
│           ┆                                                                  ┆ Classic/20250725 - Game4 - Classic vs Serral - Pylon.SC2Replay                        ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16717     ┆ 99239a9156f3d0102c5f938c04e9a5ab4b9b1733d67dd12335749b18a79d9907 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 11                  ┆ 160        ┆ 210        │
│           ┆                                                                  ┆ Classic/20250725 - Game6 - Classic vs Serral - Torches.SC2Replay                      ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16717     ┆ 99239a9156f3d0102c5f938c04e9a5ab4b9b1733d67dd12335749b18a79d9907 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 12                  ┆ 160        ┆ 210        │
│           ┆                                                                  ┆ Classic/20250725 - Game6 - Classic vs Serral - Torches.SC2Replay                      ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16718     ┆ 4d15cf43425b9bdb78770dbce0daaa7f03e3d987f565cb783ba42a044ffca789 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 13                  ┆ 168        ┆ 170        │
│           ┆                                                                  ┆ Classic/20250725 - Game7 - Classic vs Serral - Magannatha.SC2Replay                   ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16718     ┆ 4d15cf43425b9bdb78770dbce0daaa7f03e3d987f565cb783ba42a044ffca789 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 14                  ┆ 168        ┆ 170        │
│           ┆                                                                  ┆ Classic/20250725 - Game7 - Classic vs Serral - Magannatha.SC2Replay                   ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16719     ┆ 3f32defc30edd6fd9275ca96dfa5b5a3a2c3b8697c6540e865e2ef595c0265a3 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 2                   ┆ 160        ┆ 184        │
│           ┆                                                                  ┆ Classic/20250725 - Game1 - Classic vs Serral - Persephone.SC2Replay                   ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16719     ┆ 3f32defc30edd6fd9275ca96dfa5b5a3a2c3b8697c6540e865e2ef595c0265a3 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 12                  ┆ 160        ┆ 184        │
│           ┆                                                                  ┆ Classic/20250725 - Game1 - Classic vs Serral - Persephone.SC2Replay                   ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16720     ┆ 1e119307f43ba860f9ce11da3181e33545f6fa9a6937c812686079dda8ce4612 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 11                  ┆ 200        ┆ 184        │
│           ┆                                                                  ┆ Classic/20250725 - Game5 - Classic vs Serral - Ley Lines.SC2Replay                    ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16720     ┆ 1e119307f43ba860f9ce11da3181e33545f6fa9a6937c812686079dda8ce4612 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 13                  ┆ 200        ┆ 184        │
│           ┆                                                                  ┆ Classic/20250725 - Game5 - Classic vs Serral - Ley Lines.SC2Replay                    ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16721     ┆ e957b2e33ba3ba20ec12f3beb1254a5a9d716ef747c2d7322b59347bb3e89d44 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 11                  ┆ 152        ┆ 178        │
│           ┆                                                                  ┆ Classic/20250725 - Game2 - Classic vs Serral - Incorporeal.SC2Replay                  ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16721     ┆ e957b2e33ba3ba20ec12f3beb1254a5a9d716ef747c2d7322b59347bb3e89d44 ┆ /home/seb/SCReplaysOnNVMe/2025EWCReplayPack/3 - Playoffs/8 - Grand Finals - Serral vs ┆ 2       ┆ … ┆ 0       ┆ 12                  ┆ 152        ┆ 178        │
│           ┆                                                                  ┆ Classic/20250725 - Game2 - Classic vs Serral - Incorporeal.SC2Replay                  ┆         ┆   ┆         ┆                     ┆            ┆            │
└───────────┴──────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────┴─────────┴───┴─────────┴─────────────────────┴────────────┴────────────┘

In [2]:
chosen_fs_id = 16594  # One of the above

In [3]:
lobby_slot_init_data_df.collect_schema()

Schema([('ext_fs_id', UInt64),
        ('ext_fs_sha256', String),
        ('ext_fs_file_name', String),
        ('control', Int64),
        ('user_id', Int64),
        ('team_id', Int64),
        ('observe', UInt8),
        ('working_set_slot_id', UInt8),
        ('map_size_x', UInt8),
        ('map_size_y', UInt8)])

In [4]:
lobby_slot_init_data_df.describe()

shape: (9, 11)
┌────────────┬──────────────┬──────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬───┬──────────┬─────────────────────┬────────────┬────────────┐
│ statistic  ┆ ext_fs_id    ┆ ext_fs_sha256                                                    ┆ ext_fs_file_name                                                                               ┆ … ┆ observe  ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---        ┆ ---          ┆ ---                                                              ┆ ---                                                                                            ┆   ┆ ---      ┆ ---                 ┆ ---        ┆ ---        │
│ str        ┆ f64          ┆ str                                                              ┆ str                                                                                            ┆   ┆ f64      ┆ f64                 ┆ f64        ┆ f64        │
╞════════════╪══════════════╪══════════════════════════════════════════════════════════════════╪════════════════════════════════════════════════════════════════════════════════════════════════╪═══╪══════════╪═════════════════════╪════════════╪════════════╡
│ count      ┆ 587819.0     ┆ 587819                                                           ┆ 587819                                                                                         ┆ … ┆ 587819.0 ┆ 587809.0            ┆ 587819.0   ┆ 587819.0   │
│ null_count ┆ 0.0          ┆ 0                                                                ┆ 0                                                                                              ┆ … ┆ 0.0      ┆ 10.0                ┆ 0.0        ┆ 0.0        │
│ mean       ┆ 28707.742521 ┆ null                                                             ┆ null                                                                                           ┆ … ┆ 0.890808 ┆ 7.514664            ┆ 187.017909 ┆ 187.710554 │
│ std        ┆ 14907.586773 ┆ null                                                             ┆ null                                                                                           ┆ … ┆ 0.437645 ┆ 4.610149            ┆ 33.313038  ┆ 33.750313  │
│ min        ┆ 0.0          ┆ 00002a9dc36528452ad1938d035d16186b31390e6faef0487a0468214d644b34 ┆ /home/seb/SCReplaysOnNVMe/2023_07-ESL_SC2_Masters_Winter_2023_Finals/1 - Winners Stage/A1 - UB ┆ … ┆ 0.0      ┆ 0.0                 ┆ 0.0        ┆ 0.0        │
│            ┆              ┆                                                                  ┆ Ro8 #1 - GuMiho vs ShoWTimE/20230616 - Game 2 - ShoWTimE vs GuMiho - PvT - Hecate.SC2Replay    ┆   ┆          ┆                     ┆            ┆            │
│ 25%        ┆ 15545.0      ┆ null                                                             ┆ null                                                                                           ┆ … ┆ 1.0      ┆ 4.0                 ┆ 168.0      ┆ 176.0      │
│ 50%        ┆ 28331.0      ┆ null                                                             ┆ null                                                                                           ┆ … ┆ 1.0      ┆ 8.0                 ┆ 192.0      ┆ 186.0      │
│ 75%        ┆ 41635.0      ┆ null                                                             ┆ null                                                                                           ┆ … ┆ 1.0      ┆ 12.0                ┆ 200.0      ┆ 208.0      │
│ max        ┆ 54448.0      ┆ fffe9e9afdd6676125f0204935343add1386f924147125e050bdea4838f60d9f ┆ /home/seb/SCReplaysOnNVMe/[2024 GSL S2] Ro.8 Group B Match5/2SET [2024 GSL S2] Ro.8 Group B    ┆ … ┆ 2.0      ┆ 15.0                ┆ 248.0      ┆ 250.0      │
│            ┆              ┆                                                                  ┆ Match5.SC2Replay                                                                               ┆   ┆          ┆                     ┆            ┆            │
└────────────┴──────────────┴──────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴───┴──────────┴─────────────────────┴────────────┴────────────┘

In [47]:
lobby_slot_init_data_df.select(pl.col("user_id").value_counts(sort=True)).collect()
# - observe 0, 1, 2 --- 0 = player
# - control 0,1,2,3 --- unsure, most are 1.
# - user_id null, 0, 1..15 --- unsure, most are null (155Ks), then 0, 12Ks = matches number of files. 0 player number 1?
# - team_id 0, 1 --- seems for players
# - working_set_slot_id 0..15 --- unsure (are these maybe the slots of 16 players that can be in a lobby?
#   For example active players can be 12, but doesn't match the event player ids
# - map_size_x: 0? 1..16 possible values of size_x
# - map_size_y: 0? 1.. many more than 16 possible values? doesn't match size_x hmm18780

shape: (17, 1)
┌───────────────┐
│ user_id       │
│ ---           │
│ struct[2]     │
╞═══════════════╡
│ {null,436858} │
│ {0,36877}     │
│ {1,34042}     │
│ {2,18672}     │
│ {3,17298}     │
│ {4,13350}     │
│ {5,10190}     │
│ {6,7917}      │
│ {7,4209}      │
│ {8,3154}      │
│ {9,2218}      │
│ {10,1322}     │
│ {11,850}      │
│ {12,517}      │
│ {13,243}      │
│ {14,84}       │
│ {15,18}       │
└───────────────┘

In [6]:
lobby_slot_init_data_df.filter(
    [pl.col("ext_fs_id").eq(chosen_fs_id) & pl.col("observe").eq(0)]
).collect()

shape: (2, 10)
┌───────────┬──────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬───┬─────────┬─────────────────────┬────────────┬────────────┐
│ ext_fs_id ┆ ext_fs_sha256                                                    ┆ ext_fs_file_name                                                                                      ┆ control ┆ … ┆ observe ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---       ┆ ---                                                              ┆ ---                                                                                                   ┆ ---     ┆   ┆ ---     ┆ ---                 ┆ ---        ┆ ---        │
│ u64       ┆ str                                                              ┆ str                                                                                                   ┆ i64     ┆   ┆ u8      ┆ u8                  ┆ u8         ┆ u8         │
╞═══════════╪══════════════════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════╪═════════╪═══╪═════════╪═════════════════════╪════════════╪════════════╡
│ 16594     ┆ 0ac2fde9d6fcf970e1319b6276350abdce2b352fa074d6db910bed9ecef929c5 ┆ /home/seb/SCReplaysOnNVMe/2023_07-ESL_SC2_Masters_Winter_2023_Finals/1 - Winners Stage/B8 - LB Ro4a   ┆ 2       ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│           ┆                                                                  ┆ #2 - Oliveira vs Spirit/20230616 - Game 1 - Spirit vs Oliveira - TvT - Oceanborn.SC2Replay            ┆         ┆   ┆         ┆                     ┆            ┆            │
│ 16594     ┆ 0ac2fde9d6fcf970e1319b6276350abdce2b352fa074d6db910bed9ecef929c5 ┆ /home/seb/SCReplaysOnNVMe/2023_07-ESL_SC2_Masters_Winter_2023_Finals/1 - Winners Stage/B8 - LB Ro4a   ┆ 2       ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│           ┆                                                                  ┆ #2 - Oliveira vs Spirit/20230616 - Game 1 - Spirit vs Oliveira - TvT - Oceanborn.SC2Replay            ┆         ┆   ┆         ┆                     ┆            ┆            │
└───────────┴──────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴───┴─────────┴─────────────────────┴────────────┴────────────┘

In [7]:
details_df.collect_schema()

Schema([('player_name', String),
        ('player_toon_region', UInt8),
        ('player_toon_program_id', UInt32),
        ('player_toon_realm', UInt32),
        ('player_toon_id', UInt64),
        ('player_race', String),
        ('player_color_a', UInt8),
        ('player_color_r', UInt8),
        ('player_color_g', UInt8),
        ('player_color_b', UInt8),
        ('player_control', UInt8),
        ('player_team_id', UInt8),
        ('player_observe', UInt8),
        ('player_result', UInt8),
        ('player_working_set_slot_id', UInt8),
        ('player_hero', String),
        ('title', String),
        ('is_blizzard_map', Boolean),
        ('time_utc', Int64),
        ('time_local_offset', Int64),
        ('ext_fs_id', UInt64),
        ('ext_datetime', Datetime(time_unit='ns', time_zone=None))])

In [8]:
details_df.describe()

shape: (9, 23)
┌────────────┬─────────────────────────┬────────────────────┬────────────────────────┬───┬───────────┬───────────────────┬──────────────┬────────────────────────────┐
│ statistic  ┆ player_name             ┆ player_toon_region ┆ player_toon_program_id ┆ … ┆ time_utc  ┆ time_local_offset ┆ ext_fs_id    ┆ ext_datetime               │
│ ---        ┆ ---                     ┆ ---                ┆ ---                    ┆   ┆ ---       ┆ ---               ┆ ---          ┆ ---                        │
│ str        ┆ str                     ┆ f64                ┆ f64                    ┆   ┆ f64       ┆ f64               ┆ f64          ┆ str                        │
╞════════════╪═════════════════════════╪════════════════════╪════════════════════════╪═══╪═══════════╪═══════════════════╪══════════════╪════════════════════════════╡
│ count      ┆ 91696                   ┆ 91696.0            ┆ 91696.0                ┆ … ┆ 91696.0   ┆ 91696.0           ┆ 91696.0      ┆ 91696                      │
│ null_count ┆ 0                       ┆ 0.0                ┆ 0.0                    ┆ … ┆ 0.0       ┆ 0.0               ┆ 0.0          ┆ 0                          │
│ mean       ┆ null                    ┆ 1.52083            ┆ 18052.061791           ┆ … ┆ 1.3305e17 ┆ 2.5867e10         ┆ 27804.305128 ┆ 2022-08-14 06:10:42.268158 │
│ std        ┆ null                    ┆ 1.411961           ┆ 7654.836128            ┆ … ┆ 4.3868e14 ┆ 1.4581e11         ┆ 14679.558517 ┆ null                       │
│ min        ┆ &lt;0001&gt;<sp/>VOODOO ┆ 0.0                ┆ 0.0                    ┆ … ┆ 1.3240e17 ┆ -3.6000e11        ┆ 0.0          ┆ 2020-07-28 02:30:03.466019 │
│ 25%        ┆ null                    ┆ 1.0                ┆ 21298.0                ┆ … ┆ 1.3266e17 ┆ 3.6000e10         ┆ 14690.0      ┆ 2021-05-26 01:37:46.883089 │
│ 50%        ┆ null                    ┆ 2.0                ┆ 21298.0                ┆ … ┆ 1.3301e17 ┆ 3.6000e10         ┆ 26430.0      ┆ 2022-07-02 06:30:49.424632 │
│ 75%        ┆ null                    ┆ 2.0                ┆ 21298.0                ┆ … ┆ 1.3336e17 ┆ 7.2000e10         ┆ 40429.0      ┆ 2023-08-06 13:48:50.575452 │
│ max        ┆ 호에엥                  ┆ 98.0               ┆ 21298.0                ┆ … ┆ 1.3401e17 ┆ 4.6800e11         ┆ 54448.0      ┆ 2025-09-03 15:47:56.617083 │
└────────────┴─────────────────────────┴────────────────────┴────────────────────────┴───┴───────────┴───────────────────┴──────────────┴────────────────────────────┘

In [9]:
details_df.filter(pl.col("player_toon_id") != 0).select(
    pl.col("player_name").value_counts(sort=True)
).collect()

# player_name contains the clan, clan also in user_inuser_init_data_df separate from name, but no user_id/player_id there. Can be cleaned with pl.col("player_name").str.split(by="<sp/>").list.last().alias("player_name")
# player_toon_id may be 0 for A.I. game practice.
# player_race is Protoss, Terran, but also has hanzi (神族), korean? (테란) and strings like "Primal Zerg" or "Terraner" or ""
# player_team_id is either 0 or 1
# player_observe is always 0
# player_result can be 1, 2,0 and 3
#               1 is Win
#               2 is defeat
#               0 is undecided (or maybe teh status of observer?)
#               3 is  tie (there are only 50 games with this status in this 12K replay dataset.
# player_working_set_slot_id null, 0..15
#                            not the same as lobby_slot_init_data_df working_set_slot_id
# player_hero always ""
# title is the name of the map
# is_blizzard_map seems filled
# time_utc is that weird "epoch" after 2000 or something
# time_local_offset is +- in millis (or nanos?)

shape: (17_047, 1)
┌─────────────────────────────────────────┐
│ player_name                             │
│ ---                                     │
│ struct[2]                               │
╞═════════════════════════════════════════╡
│ {"&lt;Mealen&gt;<sp/>Doombringer",3226} │
│ {"&lt;chezs&gt;<sp/>Sazed",2531}        │
│ {"Sazed",1880}                          │
│ {"Massa",1661}                          │
│ {"qqq",1374}                            │
│ {"&lt;ƖIıIƖ&gt;<sp/>Sazed",744}         │
│ {"Serral",679}                          │
│ {"Reynor",669}                          │
│ {"ShoWTimE",658}                        │
│ {"Clem",580}                            │
│ {"Scarlett",507}                        │
│ {"Astrea",497}                          │
│ …                                       │
│ {"PEEDRINKER",1}                        │
│ {"&lt;ZTemp&gt;<sp/>Invictus",1}        │
│ {"Cacty",1}                             │
│ {"&lt;aqocea&gt;<sp/>Shadow",1}         │
│ {"&lt;No0Bs&gt;<sp/>Grunter",1}         │
│ {"yndgaming",1}                         │
│ {"TheShortCook",1}                      │
│ {"Neox",1}                              │
│ {"htpkBheLLioM",1}                      │
│ {"Humblesaiya",1}                       │
│ {"&lt;SALAFI&gt;<sp/>MoWjAhEeD",1}      │
│ {"BeerMan",1}                           │
└─────────────────────────────────────────┘

In [10]:
# Remove the clan from the player_name
# the clan and player are separated already in the user init data
# but I don't see a way to tie it to the lobby_state user data).
details_df = details_df.with_columns(
    pl.col("player_name").str.split(by="<sp/>").list.last().alias("player_name"),
                pl
                .when(pl.col("player_result").eq(1))
                .then(pl.lit("Win"))
                .when(pl.col("player_result").eq(2))
                .then(pl.lit("Defeat"))
                .when(pl.col("player_result").eq(0))
                .then(pl.lit("Undecided"))
                .when(pl.col("player_result").eq(3))
            .then(pl.lit("Tie"))
            .otherwise(pl.lit("Unknown"))
            .alias("game_result"),
    
)
details_df.filter(pl.col("player_toon_id") != 0).select(
    pl.col("player_name").value_counts(sort=True)
).collect()

shape: (15_930, 1)
┌──────────────────────┐
│ player_name          │
│ ---                  │
│ struct[2]            │
╞══════════════════════╡
│ {"Sazed",5180}       │
│ {"Doombringer",3226} │
│ {"Massa",1661}       │
│ {"qqq",1374}         │
│ {"Reynor",1017}      │
│ {"Serral",993}       │
│ {"HeroMarine",827}   │
│ {"ShoWTimE",808}     │
│ {"Lambo",770}        │
│ {"Astrea",748}       │
│ {"Scarlett",653}     │
│ {"ByuN",647}         │
│ …                    │
│ {"Sleven",1}         │
│ {"PEEDRINKER",1}     │
│ {"Invictus",1}       │
│ {"Cacty",1}          │
│ {"Grunter",1}        │
│ {"yndgaming",1}      │
│ {"TheShortCook",1}   │
│ {"Neox",1}           │
│ {"htpkBheLLioM",1}   │
│ {"Humblesaiya",1}    │
│ {"MoWjAhEeD",1}      │
│ {"BeerMan",1}        │
└──────────────────────┘

In [11]:
details_lobby_df = details_df.filter([pl.col("ext_fs_id").eq(chosen_fs_id)]).join(
    lobby_slot_init_data_df.filter([pl.col("ext_fs_id").eq(chosen_fs_id)]).with_columns(
        pl.col("working_set_slot_id").alias("player_working_set_slot_id")
    ),
    on="player_working_set_slot_id",
)
details_lobby_df.collect_schema()

Schema([('player_name', String),
        ('player_toon_region', UInt8),
        ('player_toon_program_id', UInt32),
        ('player_toon_realm', UInt32),
        ('player_toon_id', UInt64),
        ('player_race', String),
        ('player_color_a', UInt8),
        ('player_color_r', UInt8),
        ('player_color_g', UInt8),
        ('player_color_b', UInt8),
        ('player_control', UInt8),
        ('player_team_id', UInt8),
        ('player_observe', UInt8),
        ('player_result', UInt8),
        ('player_working_set_slot_id', UInt8),
        ('player_hero', String),
        ('title', String),
        ('is_blizzard_map', Boolean),
        ('time_utc', Int64),
        ('time_local_offset', Int64),
        ('ext_fs_id', UInt64),
        ('ext_datetime', Datetime(time_unit='ns', time_zone=None)),
        ('game_result', String),
        ('ext_fs_id_right', UInt64),
        ('ext_fs_sha256', String),
        ('ext_fs_file_name', String),
        ('control', Int64),
        ('user_id', Int64),
        ('team_id', Int64),
        ('observe', UInt8),
        ('working_set_slot_id', UInt8),
        ('map_size_x', UInt8),
        ('map_size_y', UInt8)])

In [12]:
details_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).collect()

shape: (2, 23)
┌─────────────┬────────────────────┬────────────────────────┬───────────────────┬───┬───────────────────┬───────────┬────────────────────────────┬─────────────┐
│ player_name ┆ player_toon_region ┆ player_toon_program_id ┆ player_toon_realm ┆ … ┆ time_local_offset ┆ ext_fs_id ┆ ext_datetime               ┆ game_result │
│ ---         ┆ ---                ┆ ---                    ┆ ---               ┆   ┆ ---               ┆ ---       ┆ ---                        ┆ ---         │
│ str         ┆ u8                 ┆ u32                    ┆ u32               ┆   ┆ i64               ┆ u64       ┆ datetime[ns]               ┆ str         │
╞═════════════╪════════════════════╪════════════════════════╪═══════════════════╪═══╪═══════════════════╪═══════════╪════════════════════════════╪═════════════╡
│ Spirit      ┆ 1                  ┆ 21298                  ┆ 1                 ┆ … ┆ -180000000000     ┆ 16594     ┆ 2023-12-16 04:28:43.318709 ┆ Win         │
│ Oliveira    ┆ 1                  ┆ 21298                  ┆ 1                 ┆ … ┆ -180000000000     ┆ 16594     ┆ 2023-12-16 04:28:43.318709 ┆ Defeat      │
└─────────────┴────────────────────┴────────────────────────┴───────────────────┴───┴───────────────────┴───────────┴────────────────────────────┴─────────────┘

In [13]:
upgrades_df.collect_schema()

Schema([('player_id', UInt8),
        ('name', String),
        ('count', Int32),
        ('ext_replay_loop', Int64),
        ('ext_replay_seconds', UInt32),
        ('ext_fs_id', UInt64)])

In [14]:
upgrades_df.describe()

shape: (9, 7)
┌────────────┬────────────┬───────────────────────┬────────────┬─────────────────┬────────────────────┬──────────────┐
│ statistic  ┆ player_id  ┆ name                  ┆ count      ┆ ext_replay_loop ┆ ext_replay_seconds ┆ ext_fs_id    │
│ ---        ┆ ---        ┆ ---                   ┆ ---        ┆ ---             ┆ ---                ┆ ---          │
│ str        ┆ f64        ┆ str                   ┆ f64        ┆ f64             ┆ f64                ┆ f64          │
╞════════════╪════════════╪═══════════════════════╪════════════╪═════════════════╪════════════════════╪══════════════╡
│ count      ┆ 3.083268e6 ┆ 3083268               ┆ 3.083268e6 ┆ 3.083268e6      ┆ 3.083268e6         ┆ 3.083268e6   │
│ null_count ┆ 0.0        ┆ 0                     ┆ 0.0        ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ mean       ┆ 3.133284   ┆ null                  ┆ 0.682781   ┆ 12520.396929    ┆ 609.267349         ┆ 30641.621336 │
│ std        ┆ 3.05334    ┆ null                  ┆ 1.404996   ┆ 19054.651546    ┆ 927.694957         ┆ 13549.424264 │
│ min        ┆ 0.0        ┆ 05EnergyRegen         ┆ -64.0      ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ 25%        ┆ 1.0        ┆ null                  ┆ 0.0        ┆ 0.0             ┆ 0.0                ┆ 19008.0      │
│ 50%        ┆ 2.0        ┆ null                  ┆ 1.0        ┆ 7144.0          ┆ 347.0              ┆ 33939.0      │
│ 75%        ┆ 4.0        ┆ null                  ┆ 1.0        ┆ 18668.0         ┆ 908.0              ┆ 39275.0      │
│ max        ┆ 15.0       ┆ zerglingmovementspeed ┆ 127.0      ┆ 735294.0        ┆ 35802.0            ┆ 54448.0      │
└────────────┴────────────┴───────────────────────┴────────────┴─────────────────┴────────────────────┴──────────────┘

In [15]:
upgrades_df.select(pl.col("name").value_counts(sort=True)).collect()
# player_id is 0..15
#             0 is only 20 occurrences and it's from campaign
#             From 1 it's actual players.
# name: the name of the upgrade, many are like SprayZerg/Protoss or RewardDance<Unit>
# I checked both  the s2protocol python module and debugged this one and they both are missing most of the upgardes...
# Maybe after a specific version it comes in different event type?

shape: (4_106, 1)
┌─────────────────────────────────┐
│ name                            │
│ ---                             │
│ struct[2]                       │
╞═════════════════════════════════╡
│ {"SprayZerg",391390}            │
│ {"SprayTerran",237098}          │
│ {"SprayProtoss",228103}         │
│ {"RewardDanceMule",45269}       │
│ {"zerglingmovementspeed",45221} │
│ {"RewardDanceOverlord",44670}   │
│ {"RewardDanceRoach",42782}      │
│ {"RewardDanceViking",42418}     │
│ {"RewardDanceStalker",41829}    │
│ {"MineralIncomeBonus",41200}    │
│ {"RewardDanceInfestor",39642}   │
│ {"RewardDanceOracle",39319}     │
│ …                               │
│ {"MercenaryBoostLevel36",1}     │
│ {"MercenaryBoostLevel1",1}      │
│ {"PathogenDelivery",1}          │
│ {"MercenaryBoostLevel12",1}     │
│ {"MercenaryBoostLevel13",1}     │
│ {"UpgradeShieldsColossus2",1}   │
│ {"UpgradeSpeed2",1}             │
│ {"UpgradeSpeedUltralisk",1}     │
│ {"UpgradeSpeedUltralisk2",1}    │
│ {"UpgradeJuggernautAura",1}     │
│ {"UpgradeJuggernautAura2",1}    │
│ {"UpgradeJuggernautAura3",1}    │
└─────────────────────────────────┘

In [16]:
# Clean up a little bit the upgrades:
upgrades_df = upgrades_df.filter(
    [
        ~pl.col("name").str.contains("Reward")
        & ~pl.col("name").str.contains("Spray")
        & ~pl.col("name").str.contains("GameHeart")
    ]
)
upgrades_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).collect()

shape: (9, 6)
┌───────────┬─────────────────────────────┬───────┬─────────────────┬────────────────────┬───────────┐
│ player_id ┆ name                        ┆ count ┆ ext_replay_loop ┆ ext_replay_seconds ┆ ext_fs_id │
│ ---       ┆ ---                         ┆ ---   ┆ ---             ┆ ---                ┆ ---       │
│ u8        ┆ str                         ┆ i32   ┆ i64             ┆ u32                ┆ u64       │
╞═══════════╪═════════════════════════════╪═══════╪═════════════════╪════════════════════╪═══════════╡
│ 1         ┆ InterferenceMatrix          ┆ 1     ┆ 9169            ┆ 446                ┆ 16594     │
│ 2         ┆ InterferenceMatrix          ┆ 1     ┆ 10387           ┆ 505                ┆ 16594     │
│ 2         ┆ Stimpack                    ┆ 1     ┆ 14464           ┆ 704                ┆ 16594     │
│ 1         ┆ Stimpack                    ┆ 1     ┆ 14713           ┆ 716                ┆ 16594     │
│ 1         ┆ TerranInfantryWeaponsLevel1 ┆ 1     ┆ 15058           ┆ 733                ┆ 16594     │
│ 1         ┆ TerranInfantryArmorsLevel1  ┆ 1     ┆ 15062           ┆ 733                ┆ 16594     │
│ 2         ┆ TerranInfantryArmorsLevel1  ┆ 1     ┆ 16391           ┆ 798                ┆ 16594     │
│ 2         ┆ TerranInfantryWeaponsLevel1 ┆ 1     ┆ 16391           ┆ 798                ┆ 16594     │
│ 2         ┆ ShieldWall                  ┆ 1     ┆ 16941           ┆ 824                ┆ 16594     │
└───────────┴─────────────────────────────┴───────┴─────────────────┴────────────────────┴───────────┘

In [17]:
upgrades_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
        pl.col("user_id").sub(1).alias("player_id")
    ),
    on=["player_id", "ext_fs_id"],
).collect()

shape: (9, 38)
┌───────────┬─────────────────────────────┬───────┬─────────────────┬───┬─────────┬─────────────────────┬────────────┬────────────┐
│ player_id ┆ name                        ┆ count ┆ ext_replay_loop ┆ … ┆ observe ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---       ┆ ---                         ┆ ---   ┆ ---             ┆   ┆ ---     ┆ ---                 ┆ ---        ┆ ---        │
│ u8        ┆ str                         ┆ i32   ┆ i64             ┆   ┆ u8      ┆ u8                  ┆ u8         ┆ u8         │
╞═══════════╪═════════════════════════════╪═══════╪═════════════════╪═══╪═════════╪═════════════════════╪════════════╪════════════╡
│ 1         ┆ InterferenceMatrix          ┆ 1     ┆ 9169            ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 2         ┆ InterferenceMatrix          ┆ 1     ┆ 10387           ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 2         ┆ Stimpack                    ┆ 1     ┆ 14464           ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 1         ┆ Stimpack                    ┆ 1     ┆ 14713           ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 1         ┆ TerranInfantryWeaponsLevel1 ┆ 1     ┆ 15058           ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 1         ┆ TerranInfantryArmorsLevel1  ┆ 1     ┆ 15062           ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 2         ┆ TerranInfantryArmorsLevel1  ┆ 1     ┆ 16391           ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 2         ┆ TerranInfantryWeaponsLevel1 ┆ 1     ┆ 16391           ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 2         ┆ ShieldWall                  ┆ 1     ┆ 16941           ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
└───────────┴─────────────────────────────┴───────┴─────────────────┴───┴─────────┴─────────────────────┴────────────┴────────────┘

In [18]:
stats_df.collect_schema()

Schema([('player_id', UInt8),
        ('minerals_current', Int32),
        ('vespene_current', Int32),
        ('minerals_collection_rate', Int32),
        ('vespene_collection_rate', Int32),
        ('workers_active_count', Int32),
        ('minerals_used_in_progress_army', Int32),
        ('minerals_used_in_progress_economy', Int32),
        ('minerals_used_in_progress_technology', Int32),
        ('vespene_used_in_progress_army', Int32),
        ('vespene_used_in_progress_economy', Int32),
        ('vespene_used_in_progress_technology', Int32),
        ('minerals_used_current_army', Int32),
        ('minerals_used_current_economy', Int32),
        ('minerals_used_current_technology', Int32),
        ('vespene_used_current_army', Int32),
        ('vespene_used_current_economy', Int32),
        ('vespene_used_current_technology', Int32),
        ('minerals_lost_army', Int32),
        ('minerals_lost_economy', Int32),
        ('minerals_lost_technology', Int32),
        ('vespene_lost_army', Int32),
        ('vespene_lost_economy', Int32),
        ('vespene_lost_technology', Int32),
        ('minerals_killed_army', Int32),
        ('minerals_killed_economy', Int32),
        ('minerals_killed_technology', Int32),
        ('vespene_killed_army', Int32),
        ('vespene_killed_economy', Int32),
        ('vespene_killed_technology', Int32),
        ('food_used', Int32),
        ('food_made', Int32),
        ('minerals_used_active_forces', Int32),
        ('vespene_used_active_forces', Int32),
        ('minerals_friendly_fire_army', Int32),
        ('minerals_friendly_fire_economy', Int32),
        ('minerals_friendly_fire_technology', Int32),
        ('vespene_friendly_fire_army', Int32),
        ('vespene_friendly_fire_economy', Int32),
        ('vespene_friendly_fire_technology', Int32),
        ('ext_replay_loop', Int64),
        ('ext_replay_seconds', UInt32),
        ('ext_fs_id', UInt64)])

In [19]:
stats_df.describe()

shape: (9, 44)
┌────────────┬─────────────┬──────────────────┬─────────────────┬───┬──────────────────────────────────┬─────────────────┬────────────────────┬──────────────┐
│ statistic  ┆ player_id   ┆ minerals_current ┆ vespene_current ┆ … ┆ vespene_friendly_fire_technology ┆ ext_replay_loop ┆ ext_replay_seconds ┆ ext_fs_id    │
│ ---        ┆ ---         ┆ ---              ┆ ---             ┆   ┆ ---                              ┆ ---             ┆ ---                ┆ ---          │
│ str        ┆ f64         ┆ f64              ┆ f64             ┆   ┆ f64                              ┆ f64             ┆ f64                ┆ f64          │
╞════════════╪═════════════╪══════════════════╪═════════════════╪═══╪══════════════════════════════════╪═════════════════╪════════════════════╪══════════════╡
│ count      ┆ 1.0949631e7 ┆ 1.0949631e7      ┆ 1.0949631e7     ┆ … ┆ 1.0949631e7                      ┆ 1.0949631e7     ┆ 1.0949631e7        ┆ 1.0949631e7  │
│ null_count ┆ 0.0         ┆ 0.0              ┆ 0.0             ┆ … ┆ 0.0                              ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ mean       ┆ 2.040539    ┆ 7174.973738      ┆ 1560.709325     ┆ … ┆ 6.05547                          ┆ 23920.629096    ┆ 1164.187473        ┆ 26001.120954 │
│ std        ┆ 1.358085    ┆ 1.0213e6         ┆ 11387.04092     ┆ … ┆ 104.207964                       ┆ 35527.687311    ┆ 1729.913609        ┆ 14469.151362 │
│ min        ┆ 0.0         ┆ 0.0              ┆ 0.0             ┆ … ┆ 0.0                              ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ 25%        ┆ 1.0         ┆ 125.0            ┆ 65.0            ┆ … ┆ 0.0                              ┆ 6986.0          ┆ 340.0              ┆ 13816.0      │
│ 50%        ┆ 2.0         ┆ 325.0            ┆ 232.0           ┆ … ┆ 0.0                              ┆ 14648.0         ┆ 713.0              ┆ 22697.0      │
│ 75%        ┆ 2.0         ┆ 1052.0           ┆ 724.0           ┆ … ┆ 0.0                              ┆ 25691.0         ┆ 1250.0             ┆ 38342.0      │
│ max        ┆ 15.0        ┆ 2.68435651e8     ┆ 1.323338e6      ┆ … ┆ 8500.0                           ┆ 738474.0        ┆ 35957.0            ┆ 54448.0      │
└────────────┴─────────────┴──────────────────┴─────────────────┴───┴──────────────────────────────────┴─────────────────┴────────────────────┴──────────────┘

In [20]:
stats_df.select(
    pl.col("minerals_used_in_progress_economy").value_counts(sort=True)
).collect()
# player_id From 0..14, mostly 0 and 1, not sure which matches with working_set_slot_id
# minerals_current self explanatory at a given ext_replay_loop for a specific user_id
# vespene_current same as minerals_current
# minerals_collection_rate unsure, seems to be from 0 to 14Ks, 1566 mean. maybe per minute?
# vespene_collection_rate from 0 to 4Ks, 549 mean, as with minerals_collection_rate?
# workers_active_count from 0 to 200 (oddly)
# ------ Following fields are "resource" type:
# ------ - Minerals
# ------ - Vespene
# ------ And for each resource, one stored field per "bucket"
# ------ - Army
# ------ - Economy
# ------ - Technology
# <resource>_used_in_progress_<bucket>
# <resource>_used_current_<bucket>
# <resource>_lost_<bucket>
# <resource>_killed_<bucket>
# <resource>_friendly_fire_<bucket>
# ------ And then two more:
# <resource>_used_active_forces

shape: (549, 1)
┌───────────────────────────────────┐
│ minerals_used_in_progress_economy │
│ ---                               │
│ struct[2]                         │
╞═══════════════════════════════════╡
│ {0,3645612}                       │
│ {100,963967}                      │
│ {50,853979}                       │
│ {150,760139}                      │
│ {400,651792}                      │
│ {200,495733}                      │
│ {450,457774}                      │
│ {350,456948}                      │
│ {500,380301}                      │
│ {550,254261}                      │
│ {250,234112}                      │
│ {300,194396}                      │
│ …                                 │
│ {1046,1}                          │
│ {1262,1}                          │
│ {1114,1}                          │
│ {5700,1}                          │
│ {5675,1}                          │
│ {7325,1}                          │
│ {4525,1}                          │
│ {3225,1}                          │
│ {3175,1}                          │
│ {3625,1}                          │
│ {3775,1}                          │
│ {1449,1}                          │
└───────────────────────────────────┘

In [21]:
stats_df.filter(
    [pl.col("ext_fs_id").eq(chosen_fs_id) & pl.col("ext_replay_loop").eq(1)]
).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
        pl.col("user_id").sub(1).alias("player_id")
    ),
    on=["player_id", "ext_fs_id"],
).collect()

shape: (2, 75)
┌───────────┬──────────────────┬─────────────────┬──────────────────────────┬───┬─────────┬─────────────────────┬────────────┬────────────┐
│ player_id ┆ minerals_current ┆ vespene_current ┆ minerals_collection_rate ┆ … ┆ observe ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---       ┆ ---              ┆ ---             ┆ ---                      ┆   ┆ ---     ┆ ---                 ┆ ---        ┆ ---        │
│ u8        ┆ i32              ┆ i32             ┆ i32                      ┆   ┆ u8      ┆ u8                  ┆ u8         ┆ u8         │
╞═══════════╪══════════════════╪═════════════════╪══════════════════════════╪═══╪═════════╪═════════════════════╪════════════╪════════════╡
│ 1         ┆ 50               ┆ 0               ┆ 0                        ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 2         ┆ 50               ┆ 0               ┆ 0                        ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
└───────────┴──────────────────┴─────────────────┴──────────────────────────┴───┴─────────┴─────────────────────┴────────────┴────────────┘

In [22]:
unit_born_df.collect_schema()

Schema([('unit_tag_index', UInt32),
        ('unit_tag_recycle', UInt32),
        ('unit_type_name', String),
        ('control_player_id', UInt8),
        ('upkeep_player_id', UInt8),
        ('x', Float32),
        ('y', Float32),
        ('creator_unit_tag_index', UInt32),
        ('creator_unit_tag_recycle', UInt32),
        ('creator_unit_type_name', String),
        ('creator_ability_name', String),
        ('ext_replay_loop', Int64),
        ('ext_replay_seconds', UInt32),
        ('ext_fs_id', UInt64)])

In [23]:
unit_born_df.describe()

shape: (9, 15)
┌────────────┬────────────────┬──────────────────┬─────────────────┬───┬──────────────────────┬─────────────────┬────────────────────┬──────────────┐
│ statistic  ┆ unit_tag_index ┆ unit_tag_recycle ┆ unit_type_name  ┆ … ┆ creator_ability_name ┆ ext_replay_loop ┆ ext_replay_seconds ┆ ext_fs_id    │
│ ---        ┆ ---            ┆ ---              ┆ ---             ┆   ┆ ---                  ┆ ---             ┆ ---                ┆ ---          │
│ str        ┆ f64            ┆ f64              ┆ str             ┆   ┆ str                  ┆ f64             ┆ f64                ┆ f64          │
╞════════════╪════════════════╪══════════════════╪═════════════════╪═══╪══════════════════════╪═════════════════╪════════════════════╪══════════════╡
│ count      ┆ 1.18546674e8   ┆ 1.18546674e8     ┆ 118546674       ┆ … ┆ 78572657             ┆ 1.18546674e8    ┆ 1.18546674e8       ┆ 1.18546674e8 │
│ null_count ┆ 0.0            ┆ 0.0              ┆ 0               ┆ … ┆ 39974017             ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ mean       ┆ 492.609917     ┆ 45.474343        ┆ null            ┆ … ┆ null                 ┆ 40913.449315    ┆ 1991.648966        ┆ 21629.973225 │
│ std        ┆ 288.452528     ┆ 108.590648       ┆ null            ┆ … ┆ null                 ┆ 49342.543857    ┆ 2402.544095        ┆ 13392.704394 │
│ min        ┆ 0.0            ┆ 1.0              ┆ 105mmArtillery2 ┆ … ┆                      ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ 25%        ┆ 285.0          ┆ 2.0              ┆ null            ┆ … ┆ null                 ┆ 13900.0         ┆ 676.0              ┆ 12726.0      │
│ 50%        ┆ 461.0          ┆ 10.0             ┆ null            ┆ … ┆ null                 ┆ 24770.0         ┆ 1206.0             ┆ 15350.0      │
│ 75%        ┆ 685.0          ┆ 42.0             ┆ null            ┆ … ┆ null                 ┆ 42709.0         ┆ 2079.0             ┆ 30553.0      │
│ max        ┆ 3741.0         ┆ 5169.0           ┆ zealot_A22      ┆ … ┆ toWarPig             ┆ 738474.0        ┆ 35957.0            ┆ 54448.0      │
└────────────┴────────────────┴──────────────────┴─────────────────┴───┴──────────────────────┴─────────────────┴────────────────────┴──────────────┘

In [24]:
unit_born_df.select(pl.col("creator_unit_type_name").value_counts(sort=True)).collect()
# unit_tag_index and unit_tag_recycle = used to calculate the unique id of a unit
# unit_type_name = name of unit drone, probe, mineralfield, etc.
# control_player_id Either null or 0..15
#                   When null (almost no instances in this data set) could be the campaign, stuff like K5Kerrigan
#                   When 0 it's the system creating mineral fields, geysers, etc.
#                   From 1..15 is the actual users playing.
# upkeep_player_id  Either null or 0..15
#                   As above, when 0, it's the system creating mineral fields, geysers, etc.
#                   When 1..15 actual users playing
# creator_ability_name Larva, Cocoons, OrbitalCommands, Barracks, Nexus, Lair, creating units.

shape: (1_177, 1)
┌────────────────────────────────────┐
│ creator_unit_type_name             │
│ ---                                │
│ struct[2]                          │
╞════════════════════════════════════╡
│ {"LurkerMPBurrowed",43907476}      │
│ {null,19419357}                    │
│ {"Egg",16690948}                   │
│ {"Larva",7436756}                  │
│ {"Hatchery",6536895}               │
│ {"BroodLord",3139988}              │
│ {"Barracks",2247912}               │
│ {"Nexus",1631998}                  │
│ {"OrbitalCommand",1538953}         │
│ {"BroodlingEscort",1198704}        │
│ {"BanelingCocoon",1111653}         │
│ {"Lair",1093528}                   │
│ …                                  │
│ {"BigWall",1}                      │
│ {"Keep",1}                         │
│ {"StrongBigWall",1}                │
│ {"VultureSCBW",1}                  │
│ {"SpiderMineSCBW",1}               │
│ {"MetalGateDiagonalULBRLowered",1} │
│ {"ReciepeShop",1}                  │
│ {"SiegeTower",1}                   │
│ {"ZergDropPodCreep",1}             │
│ {"OilSpill",1}                     │
│ {"EvolutionChamber3",1}            │
│ {"ugol",1}                         │
└────────────────────────────────────┘

In [25]:
unit_born_df.filter(
    [
        pl.col("ext_fs_id").eq(chosen_fs_id)
        & ~pl.col("unit_type_name").str.contains("Beacon")
    ]
).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
        pl.col("user_id").sub(1).alias("control_player_id")
    ),
    on=["control_player_id", "ext_fs_id"],
).collect()

shape: (499, 46)
┌────────────────┬──────────────────┬─────────────────┬───────────────────┬───┬─────────┬─────────────────────┬────────────┬────────────┐
│ unit_tag_index ┆ unit_tag_recycle ┆ unit_type_name  ┆ control_player_id ┆ … ┆ observe ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---            ┆ ---              ┆ ---             ┆ ---               ┆   ┆ ---     ┆ ---                 ┆ ---        ┆ ---        │
│ u32            ┆ u32              ┆ str             ┆ u8                ┆   ┆ u8      ┆ u8                  ┆ u8         ┆ u8         │
╞════════════════╪══════════════════╪═════════════════╪═══════════════════╪═══╪═════════╪═════════════════════╪════════════╪════════════╡
│ 180            ┆ 1                ┆ CommandCenter   ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 181            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 182            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 183            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 184            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 185            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 186            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 187            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 188            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 189            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 190            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 191            ┆ 1                ┆ SCV             ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ …              ┆ …                ┆ …               ┆ …                 ┆ … ┆ …       ┆ …                   ┆ …          ┆ …          │
│ 489            ┆ 2                ┆ Marine          ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 496            ┆ 3                ┆ Marine          ┆ 2                 ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 222            ┆ 3                ┆ SCV             ┆ 2                 ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 401            ┆ 2                ┆ SCV             ┆ 2                 ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 436            ┆ 1                ┆ SiegeTankSieged ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 405            ┆ 3                ┆ AutoTurret      ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 400            ┆ 6                ┆ Marine          ┆ 2                 ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 492            ┆ 2                ┆ AutoTurret      ┆ 2                 ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 210            ┆ 8                ┆ Marine          ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 205            ┆ 3                ┆ Marine          ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 232            ┆ 6                ┆ Marine          ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 307            ┆ 8                ┆ Medivac         ┆ 1                 ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
└────────────────┴──────────────────┴─────────────────┴───────────────────┴───┴─────────┴─────────────────────┴────────────┴────────────┘

In [26]:
(
    unit_born_df.filter(
        [
            pl.col("ext_fs_id").eq(chosen_fs_id)
            & ~pl.col("unit_type_name").str.contains("Beacon")
        ]
    ).join(
        details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
            pl.col("user_id").sub(1).alias("control_player_id")
        ),
        on=["control_player_id", "ext_fs_id"],
    )
    .group_by(pl.col("unit_type_name"), pl.col("player_name"))
        .agg(pl.len().alias("freq"))
        .sort(pl.col("freq"), descending=True)
    .collect()
)

shape: (71, 3)
┌──────────────────────┬─────────────┬──────┐
│ unit_type_name       ┆ player_name ┆ freq │
│ ---                  ┆ ---         ┆ ---  │
│ str                  ┆ str         ┆ u32  │
╞══════════════════════╪═════════════╪══════╡
│ SCV                  ┆ Oliveira    ┆ 90   │
│ SCV                  ┆ Spirit      ┆ 75   │
│ Marine               ┆ Spirit      ┆ 48   │
│ Marine               ┆ Oliveira    ┆ 30   │
│ SupplyDepot          ┆ Spirit      ┆ 15   │
│ SiegeTank            ┆ Spirit      ┆ 13   │
│ MULE                 ┆ Spirit      ┆ 13   │
│ SiegeTankSieged      ┆ Spirit      ┆ 12   │
│ MULE                 ┆ Oliveira    ┆ 12   │
│ SupplyDepot          ┆ Oliveira    ┆ 12   │
│ SupplyDepotLowered   ┆ Oliveira    ┆ 10   │
│ Barracks             ┆ Oliveira    ┆ 10   │
│ …                    ┆ …           ┆ …    │
│ BarracksTechLab      ┆ Spirit      ┆ 1    │
│ FactoryTechLab       ┆ Oliveira    ┆ 1    │
│ Factory              ┆ Spirit      ┆ 1    │
│ TechLab              ┆ Spirit      ┆ 1    │
│ StarportReactor      ┆ Spirit      ┆ 1    │
│ StarportReactor      ┆ Oliveira    ┆ 1    │
│ Reactor              ┆ Spirit      ┆ 1    │
│ StarportTechLab      ┆ Oliveira    ┆ 1    │
│ Armory               ┆ Oliveira    ┆ 1    │
│ OrbitalCommandFlying ┆ Spirit      ┆ 1    │
│ BarracksFlying       ┆ Spirit      ┆ 1    │
│ LiberatorAG          ┆ Spirit      ┆ 1    │
└──────────────────────┴─────────────┴──────┘

In [27]:
# System created units, mineral fields, etc.
unit_born_df.filter(
    [
        pl.col("ext_fs_id").eq(chosen_fs_id)
        & pl.col("ext_replay_loop").eq(0)
        & pl.col("control_player_id").eq(0)
    ]
).select(pl.col("unit_type_name").value_counts(sort=True)).collect()

shape: (7, 1)
┌───────────────────────────────────────────┐
│ unit_type_name                            │
│ ---                                       │
│ struct[2]                                 │
╞═══════════════════════════════════════════╡
│ {"MineralField750",56}                    │
│ {"MineralField",56}                       │
│ {"VespeneGeyser",28}                      │
│ {"DestructibleRockEx16x6",4}              │
│ {"Crabeetle",2}                           │
│ {"DestructibleRockEx1DiagonalHugeBLUR",2} │
│ {"UnbuildableRocksDestructible",2}        │
└───────────────────────────────────────────┘

In [28]:
unit_died_df.collect_schema()

Schema([('unit_died_name', String),
        ('unit_tag_index', UInt32),
        ('unit_tag_recycle', UInt32),
        ('killer_player_id', UInt8),
        ('x', UInt8),
        ('y', UInt8),
        ('unit_killer_name', String),
        ('killer_unit_tag_index', UInt32),
        ('killer_unit_tag_recycle', UInt32),
        ('ext_replay_loop', Int64),
        ('ext_replay_seconds', UInt32),
        ('ext_fs_id', UInt64)])

In [29]:
unit_died_df.describe()

shape: (9, 13)
┌────────────┬─────────────────┬────────────────┬──────────────────┬───┬─────────────────────────┬─────────────────┬────────────────────┬──────────────┐
│ statistic  ┆ unit_died_name  ┆ unit_tag_index ┆ unit_tag_recycle ┆ … ┆ killer_unit_tag_recycle ┆ ext_replay_loop ┆ ext_replay_seconds ┆ ext_fs_id    │
│ ---        ┆ ---             ┆ ---            ┆ ---              ┆   ┆ ---                     ┆ ---             ┆ ---                ┆ ---          │
│ str        ┆ str             ┆ f64            ┆ f64              ┆   ┆ f64                     ┆ f64             ┆ f64                ┆ f64          │
╞════════════╪═════════════════╪════════════════╪══════════════════╪═══╪═════════════════════════╪═════════════════╪════════════════════╪══════════════╡
│ count      ┆ 78689403        ┆ 7.8689403e7    ┆ 7.8689403e7      ┆ … ┆ 6.6145058e7             ┆ 7.8689403e7     ┆ 7.8689403e7        ┆ 7.8689403e7  │
│ null_count ┆ 0               ┆ 0.0            ┆ 0.0              ┆ … ┆ 1.2544345e7             ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ mean       ┆ null            ┆ 538.489838     ┆ 63.375421        ┆ … ┆ 30.496097               ┆ 53994.695282    ┆ 2628.556879        ┆ 19647.672575 │
│ std        ┆ null            ┆ 294.050915     ┆ 127.886213       ┆ … ┆ 72.951108               ┆ 53320.111056    ┆ 2596.253911        ┆ 12125.437447 │
│ min        ┆ 105mmArtillery2 ┆ 0.0            ┆ 1.0              ┆ … ┆ 1.0                     ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ 25%        ┆ null            ┆ 327.0          ┆ 6.0              ┆ … ┆ 3.0                     ┆ 22539.0         ┆ 1097.0             ┆ 12578.0      │
│ 50%        ┆ null            ┆ 513.0          ┆ 22.0             ┆ … ┆ 7.0                     ┆ 31549.0         ┆ 1536.0             ┆ 14650.0      │
│ 75%        ┆ null            ┆ 753.0          ┆ 68.0             ┆ … ┆ 28.0                    ┆ 68727.0         ┆ 3346.0             ┆ 22153.0      │
│ max        ┆ zealot_A22      ┆ 3741.0         ┆ 5169.0           ┆ … ┆ 4487.0                  ┆ 738465.0        ┆ 35957.0            ┆ 54448.0      │
└────────────┴─────────────────┴────────────────┴──────────────────┴───┴─────────────────────────┴─────────────────┴────────────────────┴──────────────┘

In [30]:
unit_died_df.select(pl.col("unit_killer_name").value_counts(sort=True)).collect()
# unit_died_name name of units dying.
#                Most unit names are InvisibleTargetDummy.
#                It seems when lurker or units A-move, a temporary target_dummy is created at that location and when the unit "attacks" it.
#                Q Are tank shots on InvisibleTargetDummy? There's splash radius/damage somewhere maybe?
# unit_killer_name the killer unit if found.

shape: (1_556, 1)
┌────────────────────────────────────────────────┐
│ unit_killer_name                               │
│ ---                                            │
│ struct[2]                                      │
╞════════════════════════════════════════════════╡
│ {"LurkerMPBurrowed",44307079}                  │
│ {"",17438930}                                  │
│ {"Marine",1676138}                             │
│ {"Stalker",1061259}                            │
│ {"Zergling",1032809}                           │
│ {"SiegeTankSieged",989115}                     │
│ {"Roach",737580}                               │
│ {"Hydralisk",716672}                           │
│ {"Zealot",706386}                              │
│ {"Marauder",552497}                            │
│ {"Adept",508068}                               │
│ {"Immortal",416381}                            │
│ …                                              │
│ {"DehakaMutaliskReviveEgg",1}                  │
│ {"BlightbringerBurrowed",1}                    │
│ {"TownProtossTownHallL2",1}                    │
│ {"RailgunTurretPermanent",1}                   │
│ {"CollapsibleRockTowerDebrisRampRightGreen",1} │
│ {"TierFourHuman",1}                            │
│ {"nftb",1}                                     │
│ {"RACombatMedic",1}                            │
│ {"Mortarion",1}                                │
│ {"PreserverB",1}                               │
│ {"Medic",1}                                    │
│ {"InfestedCocoon",1}                           │
└────────────────────────────────────────────────┘

In [31]:
unit_died_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
        pl.col("user_id").sub(1).alias("killer_player_id")
    ),
    on=["killer_player_id", "ext_fs_id"],
).tail(100).collect()

shape: (100, 44)
┌────────────────┬────────────────┬──────────────────┬──────────────────┬───┬─────────┬─────────────────────┬────────────┬────────────┐
│ unit_died_name ┆ unit_tag_index ┆ unit_tag_recycle ┆ killer_player_id ┆ … ┆ observe ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---            ┆ ---            ┆ ---              ┆ ---              ┆   ┆ ---     ┆ ---                 ┆ ---        ┆ ---        │
│ str            ┆ u32            ┆ u32              ┆ u8               ┆   ┆ u8      ┆ u8                  ┆ u8         ┆ u8         │
╞════════════════╪════════════════╪══════════════════╪══════════════════╪═══╪═════════╪═════════════════════╪════════════╪════════════╡
│ MULE           ┆ 328            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ MULE           ┆ 331            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ SCV            ┆ 206            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ AutoTurret     ┆ 383            ┆ 2                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ MULE           ┆ 357            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ MULE           ┆ 364            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ SCV            ┆ 263            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ SCV            ┆ 186            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ SCV            ┆ 315            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ SCV            ┆ 240            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ SCV            ┆ 273            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ AutoTurret     ┆ 425            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ …              ┆ …              ┆ …                ┆ …                ┆ … ┆ …       ┆ …                   ┆ …          ┆ …          │
│ Marine         ┆ 444            ┆ 1                ┆ 2                ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ Marine         ┆ 369            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ Marine         ┆ 379            ┆ 4                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ Marine         ┆ 197            ┆ 5                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ SCV            ┆ 236            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ Raven          ┆ 307            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ SCV            ┆ 483            ┆ 8                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ Refinery       ┆ 435            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ Marine         ┆ 495            ┆ 2                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ Medivac        ┆ 384            ┆ 4                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ SiegeTank      ┆ 428            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ MULE           ┆ 451            ┆ 1                ┆ 1                ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
└────────────────┴────────────────┴──────────────────┴──────────────────┴───┴─────────┴─────────────────────┴────────────┴────────────┘

In [32]:
len(unit_died_df.collect())

78689403

In [33]:
(
    unit_died_df
        .filter(pl.col("ext_fs_id").eq(chosen_fs_id))
        .join(
            details_lobby_df
                .filter(pl.col("ext_fs_id").eq(chosen_fs_id))
                .with_columns(pl.col("user_id").sub(1).alias("killer_player_id"))
            ,on=["killer_player_id", "ext_fs_id"],
        )
        .group_by(pl.col("player_name"), pl.col("unit_killer_name"), pl.col("unit_died_name"))
        .agg(pl.len().alias("freq"))
        .sort(pl.col("freq"), descending=True)
        .collect()
)

shape: (54, 4)
┌─────────────┬──────────────────────┬────────────────┬──────┐
│ player_name ┆ unit_killer_name     ┆ unit_died_name ┆ freq │
│ ---         ┆ ---                  ┆ ---            ┆ ---  │
│ str         ┆ str                  ┆ str            ┆ u32  │
╞═════════════╪══════════════════════╪════════════════╪══════╡
│ Spirit      ┆ OrbitalCommand       ┆ MULE           ┆ 13   │
│ Spirit      ┆ Marine               ┆ Marine         ┆ 12   │
│ Oliveira    ┆ OrbitalCommand       ┆ MULE           ┆ 10   │
│ Oliveira    ┆ Marine               ┆ Marine         ┆ 9    │
│ Spirit      ┆ Reaper               ┆ SCV            ┆ 9    │
│ Spirit      ┆ SiegeTankSieged      ┆ Marine         ┆ 8    │
│ Spirit      ┆ AutoTurret           ┆ SCV            ┆ 7    │
│ Oliveira    ┆ AutoTurret           ┆ SCV            ┆ 5    │
│ Oliveira    ┆ Cyclone              ┆ Marine         ┆ 5    │
│ Spirit      ┆ Marine               ┆ Cyclone        ┆ 4    │
│ Spirit      ┆ LiberatorAG          ┆ Marine         ┆ 4    │
│ Spirit      ┆ Reaper               ┆ KD8Charge      ┆ 3    │
│ …           ┆ …                    ┆ …              ┆ …    │
│ Oliveira    ┆ Marine               ┆ AutoTurret     ┆ 1    │
│ Spirit      ┆ Marine               ┆ Refinery       ┆ 1    │
│ Spirit      ┆ Marauder             ┆ SupplyDepot    ┆ 1    │
│ Oliveira    ┆ OrbitalCommandFlying ┆ MULE           ┆ 1    │
│ Oliveira    ┆ Cyclone              ┆ VikingFighter  ┆ 1    │
│ Spirit      ┆ Cyclone              ┆ Medivac        ┆ 1    │
│ Spirit      ┆ SiegeTankSieged      ┆ Cyclone        ┆ 1    │
│ Oliveira    ┆ Cyclone              ┆ Reaper         ┆ 1    │
│ Spirit      ┆ SiegeTankSieged      ┆ SiegeTank      ┆ 1    │
│ Oliveira    ┆ SCV                  ┆ AutoTurret     ┆ 1    │
│ Spirit      ┆ Cyclone              ┆ SupplyDepot    ┆ 1    │
│ Spirit      ┆ Marine               ┆ SupplyDepot    ┆ 1    │
└─────────────┴──────────────────────┴────────────────┴──────┘

In [46]:
cmd_target_point_df.collect_schema()

Schema([('user_id', Int64),
        ('cmd_flags', Int64),
        ('abil_link', UInt16),
        ('abil_cmd_index', Int64),
        ('ability', String),
        ('target_point_x', Int64),
        ('target_point_y', Int64),
        ('target_point_z', Int32),
        ('sequence', Int64),
        ('unit_group', UInt32),
        ('unit_name', String),
        ('ext_replay_loop', Int64),
        ('ext_replay_seconds', UInt32),
        ('ext_fs_id', UInt64)])

In [35]:
cmd_target_point_df.describe()

shape: (9, 15)
┌────────────┬─────────────┬───────────────┬─────────────┬───┬─────────────────────┬─────────────────┬────────────────────┬──────────────┐
│ statistic  ┆ user_id     ┆ cmd_flags     ┆ abil_link   ┆ … ┆ unit_name           ┆ ext_replay_loop ┆ ext_replay_seconds ┆ ext_fs_id    │
│ ---        ┆ ---         ┆ ---           ┆ ---         ┆   ┆ ---                 ┆ ---             ┆ ---                ┆ ---          │
│ str        ┆ f64         ┆ f64           ┆ f64         ┆   ┆ str                 ┆ f64             ┆ f64                ┆ f64          │
╞════════════╪═════════════╪═══════════════╪═════════════╪═══╪═════════════════════╪═════════════════╪════════════════════╪══════════════╡
│ count      ┆ 3.5858144e7 ┆ 3.5858144e7   ┆ 3.5858144e7 ┆ … ┆ 35858144            ┆ 3.5858144e7     ┆ 3.5858144e7        ┆ 3.5858144e7  │
│ null_count ┆ 0.0         ┆ 0.0           ┆ 0.0         ┆ … ┆ 0                   ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ mean       ┆ 2.155855    ┆ 59047.86063   ┆ 90.820758   ┆ … ┆ null                ┆ 3.3655e6        ┆ 230818.753739      ┆ 30352.704767 │
│ std        ┆ 2.063562    ┆ 966885.513783 ┆ 168.749814  ┆ … ┆ null                ┆ 3.0239e8        ┆ 2.0739e7           ┆ 14548.901318 │
│ min        ┆ 0.0         ┆ 256.0         ┆ 43.0        ┆ … ┆ ACPirateCapitalShip ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ 25%        ┆ 1.0         ┆ 256.0         ┆ 46.0        ┆ … ┆ null                ┆ 11917.0         ┆ 817.0              ┆ 18310.0      │
│ 50%        ┆ 2.0         ┆ 256.0         ┆ 46.0        ┆ … ┆ null                ┆ 16437.0         ┆ 1127.0             ┆ 30658.0      │
│ 75%        ┆ 3.0         ┆ 256.0         ┆ 46.0        ┆ … ┆ null                ┆ 21948.0         ┆ 1505.0             ┆ 42890.0      │
│ max        ┆ 15.0        ┆ 5.0331904e7   ┆ 4058.0      ┆ … ┆ herochooser         ┆ 2.7646e10       ┆ 1.8960e9           ┆ 54448.0      │
└────────────┴─────────────┴───────────────┴─────────────┴───┴─────────────────────┴─────────────────┴────────────────────┴──────────────┘

In [36]:
cmd_target_point_df.select(pl.col("ability").value_counts(sort=True)).collect()
# map_elements(lambda x: f'{x:>064b}', return_dtype=pl.String). # Transform i64 to bits.
# cmd_flags is some bit map, not sure about its meaning. Mostly 0s, a few 1s
# unst_abil is a currently unstable feature of s2protocol-rs that tries to generate the ability strings.
# abil_link: mostly null, then followed by 46, 172, 185, 267
# abil_cmd_index: From 0 to 15, mostly nulls, followed by  0, 1,3,15,4,...
# target_point_x, target_point_y and target_point_z are self explanatory, important that the Z is i32 and x,y are i64 at the source.
# sequence: Unknown 12K values, top are: 5,6,4,7,721,681,...
# unit_group: 20 values, most are null, then 70011 with 44 instances, 69957, 70013, but very very few non nulls.

shape: (101, 1)
┌───────────────────────────────────┐
│ ability                           │
│ ---                               │
│ struct[2]                         │
╞═══════════════════════════════════╡
│ {"",35347087}                     │
│ {"attack.Execute",393636}         │
│ {"Build.CreepTumorQueen",19763}   │
│ {"Build.Pylon",7122}              │
│ {"Train.Zealot",6918}             │
│ {"Build.SupplyDepot",6566}        │
│ {"Build.SporeCrawler",5369}       │
│ {"Build.Hatchery",4846}           │
│ {"Blink.Execute",4509}            │
│ {"Build.Barracks",3510}           │
│ {"Train.Stalker",3462}            │
│ {"Build.Gateway",3403}            │
│ …                                 │
│ {"RallyHatchery.Rally2",23}       │
│ {"OrbitalCommandLand.Execute",22} │
│ {"BarracksLand.Execute",22}       │
│ {"SprayProtoss.Execute",15}       │
│ {"FactoryLand.Execute",12}        │
│ {"TemporalField.Execute",9}       │
│ {"StarportLand.Execute",4}        │
│ {"TacNukeStrike.Execute",4}       │
│ {"SprayTerran.Execute",4}         │
│ {"SporeCrawlerRoot.Execute",3}    │
│ {"CommandCenterLand.Execute",3}   │
│ {"MassRecall.Execute",2}          │
└───────────────────────────────────┘

In [37]:
cmd_target_point_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
        pl.col("user_id").alias("user_id")
    ),
    on=["user_id", "ext_fs_id"],
).sort(by=[pl.col("ext_replay_loop")]).collect()

shape: (386, 45)
┌─────────┬───────────┬───────────┬────────────────┬───┬─────────┬─────────────────────┬────────────┬────────────┐
│ user_id ┆ cmd_flags ┆ abil_link ┆ abil_cmd_index ┆ … ┆ observe ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---     ┆ ---       ┆ ---       ┆ ---            ┆   ┆ ---     ┆ ---                 ┆ ---        ┆ ---        │
│ i64     ┆ i64       ┆ u16       ┆ i64            ┆   ┆ u8      ┆ u8                  ┆ u8         ┆ u8         │
╞═════════╪═══════════╪═══════════╪════════════════╪═══╪═════════╪═════════════════════╪════════════╪════════════╡
│ 3       ┆ 256       ┆ 131       ┆ 3              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 2       ┆ 258       ┆ 43        ┆ 1              ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 2       ┆ 131328    ┆ 131       ┆ 3              ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 3       ┆ 258       ┆ 43        ┆ 1              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 43        ┆ 1              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 131       ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 2       ┆ 256       ┆ 131       ┆ 0              ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 2       ┆ 256       ┆ 131       ┆ 10             ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 131       ┆ 1              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 2       ┆ 256       ┆ 131       ┆ 1              ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 3       ┆ 65792     ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 258       ┆ 43        ┆ 1              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ …       ┆ …         ┆ …         ┆ …              ┆ … ┆ …       ┆ …                   ┆ …          ┆ …          │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 2       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 2       ┆ 256       ┆ 268       ┆ 0              ┆ … ┆ 0       ┆ 2                   ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
│ 3       ┆ 256       ┆ 46        ┆ 0              ┆ … ┆ 0       ┆ 14                  ┆ 200        ┆ 194        │
└─────────┴───────────┴───────────┴────────────────┴───┴─────────┴─────────────────────┴────────────┴────────────┘

In [38]:
cmd_target_point_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id))
    .filter(pl.col("player_race").eq("Zerg"))
    .select(pl.col(["user_id", "ext_fs_id"])),
    on=["user_id", "ext_fs_id"],
).sort(by=[pl.col("ext_replay_loop")]).select(
    pl.col("abil_link").value_counts(sort=True)
).collect()

shape: (0, 1)
┌───────────┐
│ abil_link │
│ ---       │
│ struct[2] │
╞═══════════╡
└───────────┘

In [39]:
cmd_target_point_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id))
    .filter(pl.col("player_race").eq("Protoss"))
    .select([pl.col("user_id"), pl.col("ext_fs_id")]),
    on=["user_id", "ext_fs_id"],
).sort(by=[pl.col("ext_replay_loop")]).select(
    pl.col("abil_link").value_counts(sort=True)
).collect()

shape: (0, 1)
┌───────────┐
│ abil_link │
│ ---       │
│ struct[2] │
╞═══════════╡
└───────────┘

In [40]:
cmd_target_unit_df.collect_schema()

Schema([('user_id', Int64),
        ('cmd_flags', Int64),
        ('abil_link', UInt16),
        ('abil_cmd_index', Int64),
        ('ability', String),
        ('target_unit_flags', UInt16),
        ('tag', UInt32),
        ('snapshot_unit_link', UInt16),
        ('snapshot_control_player_id', Int64),
        ('snapshot_upkeep_player_id', Int64),
        ('snapshot_point_x', Int64),
        ('snapshot_point_y', Int64),
        ('snapshot_point_z', Int32),
        ('sequence', Int64),
        ('unit_name', String),
        ('target_unit_name', String),
        ('ext_replay_loop', Int64),
        ('ext_replay_seconds', UInt32),
        ('ext_fs_id', UInt64)])

In [41]:
cmd_target_unit_df.describe()

shape: (9, 20)
┌────────────┬────────────┬──────────────┬────────────┬───┬──────────────────┬─────────────────┬────────────────────┬──────────────┐
│ statistic  ┆ user_id    ┆ cmd_flags    ┆ abil_link  ┆ … ┆ target_unit_name ┆ ext_replay_loop ┆ ext_replay_seconds ┆ ext_fs_id    │
│ ---        ┆ ---        ┆ ---          ┆ ---        ┆   ┆ ---              ┆ ---             ┆ ---                ┆ ---          │
│ str        ┆ f64        ┆ f64          ┆ f64        ┆   ┆ str              ┆ f64             ┆ f64                ┆ f64          │
╞════════════╪════════════╪══════════════╪════════════╪═══╪══════════════════╪═════════════════╪════════════════════╪══════════════╡
│ count      ┆ 7.642403e6 ┆ 7.642403e6   ┆ 7.642403e6 ┆ … ┆ 7642403          ┆ 7.642403e6      ┆ 7.642403e6         ┆ 7.642403e6   │
│ null_count ┆ 0.0        ┆ 0.0          ┆ 0.0        ┆ … ┆ 0                ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ mean       ┆ 1.826426   ┆ 1947.829012  ┆ 200.424693 ┆ … ┆ null             ┆ 1.0802e7        ┆ 740818.439354      ┆ 27392.179499 │
│ std        ┆ 2.113616   ┆ 220888.11062 ┆ 245.002691 ┆ … ┆ null             ┆ 5.4535e8        ┆ 3.7403e7           ┆ 14736.65575  │
│ min        ┆ 0.0        ┆ 256.0        ┆ 43.0       ┆ … ┆                  ┆ 0.0             ┆ 0.0                ┆ 0.0          │
│ 25%        ┆ 0.0        ┆ 256.0        ┆ 46.0       ┆ … ┆ null             ┆ 9268.0          ┆ 635.0              ┆ 14285.0      │
│ 50%        ┆ 1.0        ┆ 256.0        ┆ 113.0      ┆ … ┆ null             ┆ 14945.0         ┆ 1024.0             ┆ 25062.0      │
│ 75%        ┆ 3.0        ┆ 256.0        ┆ 247.0      ┆ … ┆ null             ┆ 24148.0         ┆ 1656.0             ┆ 40275.0      │
│ max        ┆ 15.0       ┆ 3.355469e7   ┆ 4002.0     ┆ … ┆ Zergling         ┆ 2.7646e10       ┆ 1.8960e9           ┆ 54448.0      │
└────────────┴────────────┴──────────────┴────────────┴───┴──────────────────┴─────────────────┴────────────────────┴──────────────┘

In [42]:
cmd_target_unit_df.select(pl.col("ability").value_counts(sort=True)).collect()
# User-ID is 0-indexed
# cmd_flags 8 values, seems bitmap
# ability: the translated ability after parsing the BalanceData XML, only available for latest version.
# abil_link: mostly null, then followed by 46, 172, 185, 267
# abil_cmd_index: 7 possible values, mostly nulls, followed by  0,2,1,3,23,18
# target_unit_flags can be either 111 or 175 I guess some bitmap
# tag: The tag_index+tag_recycle combo
# snapshot_unit_link 321 possible values, top are 545,109,903,111,547,... Maybe related to abil_link?
# snapshot_control_player_id from 0 to 15
# snapshot_upkeep_player_id 0 to 15
# snapshot_pointx, y, z positions, again z is i32.
# sequence 9K values, starts at 2, 1, 6, 3,66, 82,68 maybe bitmap

shape: (45, 1)
┌─────────────────────────────────────────┐
│ ability                                 │
│ ---                                     │
│ struct[2]                               │
╞═════════════════════════════════════════╡
│ {"",7471735}                            │
│ {"Transfusion.Execute",74311}           │
│ {"attack.Execute",38283}                │
│ {"SpawnLarva.Execute",14164}            │
│ {"ChronoBoostEnergyCost.Execute",10203} │
│ {"SCVHarvest.Gather",9680}              │
│ {"Build.Extractor",5995}                │
│ {"Build.Refinery",3476}                 │
│ {"DroneHarvest.Gather",2212}            │
│ {"Build.Assimilator",1818}              │
│ {"EnergyRecharge.Execute",1665}         │
│ {"Repair.Execute",1637}                 │
│ …                                       │
│ {"LockOn.Execute",40}                   │
│ {"RavenShredderMissile.Execute",33}     │
│ {"WarpPrismTransport.Load",32}          │
│ {"BattlecruiserAttack.Execute",15}      │
│ {"RavenScramblerMissile.Execute",13}    │
│ {"Contaminate.Execute",12}              │
│ {"MedivacTransport.Load",8}             │
│ {"OverlordTransport.UnloadAt",7}        │
│ {"RallyHatchery.Rally1",6}              │
│ {"ShieldBatteryRechargeEx5.Execute",4}  │
│ {"AttackRedirect.Execute",3}            │
│ {"MULEGather.Gather",2}                 │
└─────────────────────────────────────────┘

In [43]:
cmd_target_unit_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
        pl.col("user_id").alias("user_id")
    ),
    on=["user_id", "ext_fs_id"],
).filter(pl.col("ability") != "").sort(by=[pl.col("ext_replay_loop")]).collect()

shape: (0, 50)
┌─────────┬───────────┬───────────┬────────────────┬───┬─────────┬─────────────────────┬────────────┬────────────┐
│ user_id ┆ cmd_flags ┆ abil_link ┆ abil_cmd_index ┆ … ┆ observe ┆ working_set_slot_id ┆ map_size_x ┆ map_size_y │
│ ---     ┆ ---       ┆ ---       ┆ ---            ┆   ┆ ---     ┆ ---                 ┆ ---        ┆ ---        │
│ i64     ┆ i64       ┆ u16       ┆ i64            ┆   ┆ u8      ┆ u8                  ┆ u8         ┆ u8         │
╞═════════╪═══════════╪═══════════╪════════════════╪═══╪═════════╪═════════════════════╪════════════╪════════════╡
└─────────┴───────────┴───────────┴────────────────┴───┴─────────┴─────────────────────┴────────────┴────────────┘

In [44]:
cmd_target_unit_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
        pl.col("user_id").alias("user_id")
    ),
    on=["user_id", "ext_fs_id"],
).filter(pl.col("ability") != "").group_by(pl.col("ability"), pl.col("player_name")).agg(pl.len().alias("freq")).sort(pl.col("freq"),descending=True).collect()

shape: (0, 3)
┌─────────┬─────────────┬──────┐
│ ability ┆ player_name ┆ freq │
│ ---     ┆ ---         ┆ ---  │
│ str     ┆ str         ┆ u32  │
╞═════════╪═════════════╪══════╡
└─────────┴─────────────┴──────┘

In [45]:
cmd_target_unit_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).join(
    details_lobby_df.filter(pl.col("ext_fs_id").eq(chosen_fs_id)).with_columns(
        pl.col("user_id").alias("user_id")
    ),
    on=["user_id", "ext_fs_id"],
).filter(
    pl.col("ability").str.starts_with("Build.")
).group_by(pl.col("ability"), pl.col("player_name")).agg(pl.len().alias("freq")).sort(pl.col("freq"),descending=True).collect()

shape: (0, 3)
┌─────────┬─────────────┬──────┐
│ ability ┆ player_name ┆ freq │
│ ---     ┆ ---         ┆ ---  │
│ str     ┆ str         ┆ u32  │
╞═════════╪═════════════╪══════╡
└─────────┴─────────────┴──────┘